### PR TITLE
Made Command class abstract

### PR DESCRIPTION
**Pull request by dumaike**
The Command class should be abstract and so should it's Execute method. Currently this method throws a run time exception if not overridden, but it's better to get compile time errors if you're inheriting from Command and not implementing Execute.

### CODE REVIEW

**Comment by WillzZz** [comment]
Yup. Fix the tests please?

**Comment by dumaike** [comment]
I didn't notice tests that were broken. The "dev_test_scene" in unity seemed to still run fine. Is there another test I'm missing?

**Comment by WillzZz** [comment]
Yup, TestCommand will definitely break. it's explicitly testing this with classes like "CommandWithoutExecute".

**Comment by dumaike** [comment]
I found the testing files. They were in a ".test" folder and I had tested in Unity so Unity wasn't pulling them in until I removed the "."

I updated those classes to throw the same exception in the abstract error implementation that Command.cs used to throw. I'm having trouble being able to run the solution/tests to make sure I've covered all the bases correctly though.

When I try to compile these tests in Unity I get compile errors that NUnit is missing. I can build the source outside Unity by including the NUnit Visual Studio Plugin, but then I get errors about missing Unity classes in things like  (GameObject etc.)

I set up a unreliable hybrid by using UnityVS to build a Visual Studio solution with Unity dependencies and then included NUnit in that solution, but then I've got inexplicable errors that don't look like anything I modified. For example, in [TestBindingAsPoolFacade.cs](https://github.com/strangeioc/strangeioc/blob/master/StrangeIoC/scripts/strange/.tests/framework/TestBindingAsPoolFacade.cs) it seems that the PooledInstanceForBinding (Line 263) doesn't properly implement it's interface? Is this related to something I've changed or are these tests not fully up to date? Are there build instructions somewhere I'm missing?

**Comment by fogAndWhisky** [comment]
Yeah, Unity throws a fit if it runs across NUnit tests....but it'll ignore them if the directory begins with a dot. As to any incomparability with VS, Ill leave that to Will, who understands its peculiarities far better than I. 

Just to put you in the right frame, though, all tests are up-to-date on 'tip' and there's one  known test failure (to do with PostConstruct) on 'master'. Any other test failures are more likely a setup or config problem on your end. 

Your change is on-the-money, though, so let's fix this for the upcoming release.

**Comment by WillzZz** [comment]
I use resharper and dotcover to run my tests. I'm not sure what method anyone else uses in VS. If you're using VS, you owe it to yourself to have resharper. I can't recommend it enough.

**Comment by WillzZz** [comment]
Let's re-open this against tip.

**Pull request closed without merging**
