### PR TITLE
Fixed MVCSContext to bind the IMediationBinder to the SignalMediation…

### PR DESCRIPTION
**Pull request by jedh**
…Binder to allow for the ListensTo attribution to work.

### CODE REVIEW

**Comment by WillzZz** [comment]
Hmmm.. this definitely works but it implies we are using this as the default. I'm not sure how to take a general consensus on whether it should be default or not. I'm slightly leaning towards this being the correct answer, though.

**Comment by jedh** [comment]
I guess I'm not sure what would be missed? It seems to me that the standard way of manually calling .AddListener still works, both when bubbling up from a view and when declaring it in OnRegister.

I guess if that's the case too, with it being default I don't know if it also might be a good idea to have the SignalCommandBinder bound to the ICommandBinder by default as well?

**Comment by WillzZz** [comment]
That's true, it could be time to set signal command binder to be the default. 1.0 is a good time for breaking changes, even if it's a minor one.

**Comment by WillzZz** [comment]
Approved.

**Pull request merged**
