### PR TITLE
Basic Promise

### PR DESCRIPTION
**Pull request by WillzZz**
Promises! 

So this is a q-promise-esque implementation. Methods include Then, Fail, Progress and Finally. They should work exactly as you expect. I wrote a buttload of tests to cover everything well. dotCover seems to agree.

Promises are best used as you would an Injected Signal.

[Inject]
public MyPromise MyPromise { get; set; }

Often you'll have one-shot signals which represent a single action in your code. All  you really care is if your action has happened or not. This is the simplest case for a Promise!

Instead of checking if a value is set on some model or using a clunky double dispatch signal,  you can use a promise!

Where you previously might write:

if (DataModel.DataSet)
{
    DoStuff();
}
else
{
 DataSignal.AddListener(DoStuff);
}

you can now just write this:

DataPromise.Then(DoStuff);

This is the most basic use case for promise. Anything that happens once. A promise also stores the dispatched data!

So a Promise<T,U> will hold on to its values t and u after the initial Dispatch. Every time after Dispatch when you call Then(), you will pass it along each time.

You can rely on your promise decoupling you from whatever logic you might need it for. Here's an example of a Promise with args.

MyPromise.Dispatch(42, "MySpecialString")
MyPromise.Then(MyCallback)
void MyCallback(int myInt, String myString)

Now for some more advanced techniques. In q-promises, these would be considered Deferred Calls. More or less!

By using Methods which conform to the C# Delegate Func<IPromise, T> we can create methods which return Promises and allow us to wrap our async calls and rely on the decoupling from Promises to write our code in a simple one-directional way.

Given a method:

Promise<int> DownloadFile(String url)
{
    StartCoroutine(GetMyFile())
    return MyDownloadPromise;
}

We can write the following line to make a slick async flow:

DownloadFile(url)
    .Then(DoSomethingWithTheFile)
    .Progress(UpdateFileProgress)
    .Fail(OnDownloadFile)
    .Finally(CleanupWWW)

Important side notes:
- Progress, Fail, and Dispatch methods all need to be utilized on the Promise in order for any of these methods to work. 

- Fail is not a try/catch mechanism. It needs to be called manually. If we could make that more automatic, that'd be cool.

- Writing a proper deferred call wrapper requires some slow reflection, so I wrote it off immediately.

- I didn't include a deferred call wrapper similar to Q.fcall. I couldn't see the benefit, but if anyone can find a benefit, by all means let me know.

### CODE REVIEW

**Comment by WillzZz** [comment]
Yup, originally had one. Deleted it because it had no implementable methods.  I do want one.

**Comment by fogAndWhisky** [comment]
OK...I get what you're saying about "All I really needed was a way to defuse race conditions" and I agree we don't need to go as far as full-on Q-promise on a V1, but I wonder if for general usefulness we should broaden this a little bit. In particular, I'm thinking we should implement (1) a progress method so the deferrer can hand back updates during loading, and (2) catch/finally methods for error handling?

**Comment by fogAndWhisky** [comment]
Something on this branch is kinda borked. The obvious issues relate to references to files no longer there (Promise.cs in the Signals package and TestPromise.cs in the Signals test package) and a reference to a pre-release version of Unity itself for the reference to the UnityEngine.DLL. But even after fixing these, I was still unable to get unit tests to run in Xamarin. After burning a couple hours on this, I think I'll hand it back to @WillzZz to hopefully unravel.

**Comment by Kl0tl** [comment]
Hi everyone, thanks for your work on StrangeIOC !

Coming from a Javascript background i’m excited to see promises landing in Strange but also a bit confused. Why are promises responsible for their resolution ? Wouldn’t it be better to let this to another type (i’m looking at you `Deferred`) or expose the resolve/reject/progress triple to a delegate passed to the constructor ?

Am I missing any reason to not follow common implementations ?

**Comment by unitymarc** [comment]
@Kl0tl First off, thanks for participating in the conversation. We need more people doing this before we finalize any new feature!

As an Angular dev by day, I tend to agree with you. I'm more used to passing resolution to 'deferred.resolve()'. That said, I'm satisfied with @WillzZz's implementation as a simple structure that does everything we need it to do. We're both open to good arguments, though (and it's certain we haven't thought of every possible outcome). Can you explain a use case where the current implementation would be insufficient?

**Comment by WillzZz** [comment]
My first implementation used Deferred, as you would expect. It ended up being a wrapper around Func and almost entirely pointless. C# does enough for us, to be honest. I'm happy to explore more use cases and tinker with the functionality, though.

**Comment by Kl0tl** [comment]
It mostly feels weird to me to let the consumer be able to resolve himself a promise. Besides that I don’t think it limits our use cases but many people have thought about and worked on the Promise spec in Javascript-land and we could be missing something.

**Comment by Kl0tl** [comment]
Just thinking about use cases,  `Promise.All()` and `Promise.Race()` could be useful to help composing promises. What do you think ?

**Comment by unitymarc** [comment]
> It mostly feels weird to me to let the consumer be able to resolve himself a promise

Isn't it the implementer that resolves? The consumer simply uses it.

With Promise.All(), I take this to mean "Here are multiple promises. Call Then() after all of them are resolvable." Is that what you mean? I like that...though I'm not sure we need it in V1 (might be best not to get too ambitious with a new feature).

I'm not sure what you're getting at with Promise.Race()...or in what way that might differ from All(). All, at least as I've interpreted above, pretty much presumes a possible race condition. If that's a feature of Angular's $q, then it's one I've never used. :)

**Comment by Kl0tl** [comment]
If `Dispatch()` is public any consumer can resolve the promise before the producer does. It’s not a big deal I guess but shouldn’t the API disallow this ?

It’s exactly what I meant for `Promise.All()` ! I quite often use this utility while working with promises but I agree it might be best to see if it is that useful in Strange-land. It’s not too difficult to implement manually anyway. Just something to keep in mind and eventually teach people about it.

Instead of waiting for the resolution of many promises, Promise.Race() resolves or rejects with the first promise that do. It’s useful to easily cancel something based on a timeout or another async action but I didn’t see it often before the Promise standardisation in ES6. The same concerns than `Promise.All()` regarding its usefulness in v1 apply.

**Comment by srimarc** [comment]
Ok, I grant you, the race concept is cool. :) again, possibly not v1, but undeniably good to know about. 

Leaving this here for reference. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Now, as to the public nature of Dispatch....I think @WillzZz should address this. To my thinking, the method *has to be* public. If you look at my blog post example, how would even the implementer call promise.Dispatch() if this weren't so? Yes, it is open to abuse.

I suppose, if we were to be very worried about this, that would be the argument for wrapping promise inside deferred....it exposes an API for the implementer to resolve without exposing that same API to the consumer. Thoughts Will?

**Comment by Kl0tl** [comment]
After thinking about it couldn’t we follow the ES6 way and expose `Dispatch()` and `ReportFail()` to a lambda passed to the promise constructor ?

Taking your example, it could look like this:

```cs
private IPromise<string> promise;
public IPromise<string> FetchLevelName ()
{
    if (promise == null) {
        promise = new Promise<string>((resolve) => {
            StartCoroutine(FetchLevelNameFromServer(resolve));
        });
    }

    return promise;
}

private IEnumerator FetchLevelNameFromServer (resolve)
{
    WWW www = new WWW('http://myserver/get/the/level');
    yield return www;
    resolve(www.text);
}
```

The major difference is the null check but since promises can’t be resolved twice we don’t want to call `FetchLevelNameFromServer()` more than once anyway, do we ?

**Comment by simon129** [comment]
there is another promise lib. for unity, take a look https://www.assetstore.unity3d.com/en/#!/content/15604

**Comment by WillzZz** [comment]
Happy to consider PRs to promises.

I'm not sure adding loads of boilerplate to circumvent dispatch being public (and using it in essentially an identical manner) is worth while. Simplicity plays some role. Being able to dispatch from two locations could also be useful. I don't feel that public access to Dispatch is an inherent negative or API flaw. I can be convinced otherwise with example edge cases, of course.

Adding cleanup and then merging this if Marc gives the ok.

**Comment by Kl0tl** [comment]
With a public `Dispatch()` there is no guarantee that only the producer will resolve the promise. If the promise is passed around it could be harder to understand who produce the value and who is simply a consumer whereas it’s trivial when you separate the resolution mechanism from the promise.

It may also encourage folks to abuse this as a sort of cancelation strategy without having to notify the producer. While far fetched it could lead to subtle, hard to understand bugs.

Besides that, Promises are supposed to represent values that are not yet available. Why a consumer would request a promise if it already has the value the promise fulfills to ? Shouldn’t the API emphasizes that ?

Resolving the promise from another location is definitively useful though but neither of the other approaches disallow it.

**Comment by WillzZz** [comment]
This should be ready for RC and pull @fogAndWhisky . And thanks very much for all of the valuable feedback! Our RC release will likely remain simple but all of your help is greatly, greatly appreciated!

**Comment by Kl0tl** [comment]
Let me know if you could use any help on Strange, enjoyed this conversation !

**Comment by WillzZz** [comment]
Merging to tip, further testing can happen there.

**Pull request merged**
